### ISSUE TITLE
Unable to connect to Merriam-Webster dictionary

### ISSUE THREAD

**Issue by tetrapharmakon** [paolobrasolin/tex-ipenama#5]
Output I see when launching the file from any repo:

```
5z [fouche:~/loca-copy] ± ipenama localization
Latexmk: This is Latexmk, John Collins, 7 August 2018, version: 4.59.
Latexmk: All targets (ipenama/localization.dvi) are up-to-date
   1 of   58: ? additional (adÂ·​diÂ·​tionÂ·​al)
   2 of   58: ✗ adhoc
   3 of   58: ? applications (apÂ·​pliÂ·​caÂ·​tion)
   4 of   58: ? arrangement (arÂ·​rangeÂ·​ment)
   5 of   58: ? associated (asÂ·​soÂ·​ciÂ·​atÂ·​ed)
   6 of   58: ? calligraphic (calÂ·​ligÂ·​raÂ·​phy)
...
```
words are either not found or dumped in `log_dup`.

Upon further investigation, the issue seems related to the fact that in the `xpath` code at [line 48](https://github.com/paolobrasolin/tex-ipenama/blob/master/ipenama.py#L48) catches a [zero width space](http://www.fileformat.info/info/unicode/char/200B/index.htm) after the bullet separating syllables. The current search function does not seem to remove it properly.

**Comment by paolobrasolin** [comment]
Excellent bug report. Merriam Webster did in fact change the syllable separator. Easily fixed.
